/**
 * Preprocessor fixtures: [name, PICO-8 source, expected Lua 5.4 body].
 * The expected Lua excludes the helper-locals prefix emitted on line 1.
 */
export const FIXTURES: [string, string, string][] = [
  ["compound add", "x+=1", "x=(x+(1.0));"],
  ["compound ops arith", "a-=1 b*=2 c/=3 d%=4 e^=2", "a=(a-(1.0));b=(b*(2.0));c=(c/(3.0));d=(d%(4.0));e=(e^(2.0));"],
  ["compound idiv", "a\\=2", "a=(a//(2.0));"],
  ["compound concat", "s..=\"x\"", "s=__p8_cat(s,(\"x\"));"],
  ["compound bitwise", "a|=1 b&=3 c^^=5", "a=__p8_bor(a,(1.0));b=__p8_band(b,(3.0));c=__p8_bxor(c,(5.0));"],
  ["compound shifts", "a<<=1 b>>=2 c>>>=3 d<<>=4 e>><=5", "a=__p8_shl(a,(1.0));b=__p8_shr(b,(2.0));c=__p8_lshr(c,(3.0));d=__p8_rotl(d,(4.0));e=__p8_rotr(e,(5.0));"],
  ["compound complex lhs", "a.b[c]+=1", "a.b[c]=(a.b[c]+(1.0));"],
  ["compound method-call index", "t[f(x)].y-=d*2", "t[f(x)].y=(t[f(x)].y-((d*2.0)));"],
  ["two compounds one line", "b.x+=b.dx b.y+=b.dy", "b.x=(b.x+(b.dx));b.y=(b.y+(b.dy));"],
  ["compound rhs call then stmt", "x+=f(1) y=2", "x=(x+(f(1.0)));y=2.0;"],
  ["compound rhs multiline", "x+=a+\n b", "x=(x+((a+\nb)));"],
  ["not-equal", "if a!=b then c=1 end", "if(a~=b)then c=1.0;end;"],
  ["short if", "if (x>1) y=2", "if((x>1.0))then y=2.0;end;"],
  ["short if else", "if (a) b=1 else b=2", "if(a)then b=1.0;else b=2.0;end;"],
  ["short if multiple stmts", "if (a) b=1 c=2\nd=3", "if(a)then b=1.0;c=2.0;end;\nd=3.0;"],
  ["short if nested", "if (a) if (b) c=1", "if(a)then if(b)then c=1.0;end;end;"],
  ["short if return", "function f(a)\nif (a) return\nreturn 1\nend", "function f(a)\nif(a)then return;end;\nreturn 1.0;\nend"],
  ["short if with call cond", "if (btn(0)) x-=1", "if(btn(0.0))then x=(x-(1.0));end;"],
  ["short while", "while (i<3) i+=1", "while((i<3.0))do i=(i+(1.0));end;"],
  ["if do", "if a do b() end", "if a then b();end;"],
  ["print shorthand", "?\"hi\"..1", "print(__p8_cat(\"hi\",1.0));"],
  ["print shorthand args", "?x,1,2,7", "print(x,1.0,2.0,7.0);"],
  ["integer division", "a=7\\2", "a=(7.0//2.0);"],
  ["bitwise ops", "a=b&c|d^^e", "a=__p8_bor(__p8_band(b,c),__p8_bxor(d,e));"],
  ["bnot", "a=~b", "a=__p8_bnot(b);"],
  ["shifts", "a=b<<1 c=d>>2 e=f>>>3 g=h<<>4 i=j>><5", "a=__p8_shl(b,1.0);c=__p8_shr(d,2.0);e=__p8_lshr(f,3.0);g=__p8_rotl(h,4.0);i=__p8_rotr(j,5.0);"],
  ["peek ops", "a=@0x5f00 b=%0x5f01 c=$0x5f02", "a=__p8_peek(24320.0);b=__p8_peek2(24321.0);c=__p8_peek4(24322.0);"],
  ["binary literal", "a=0b1010", "a=10.0;"],
  ["hex fraction", "a=0x5a5a.8", "a=23130.5;"],
  ["binary fraction", "a=0b1.1", "a=1.5;"],
  ["fixed-point literal", "a=.1", "a=0.0999908447265625;"],
  ["wrap literal", "a=0xffff b=32768 c=-32768", "a=(-1.0);b=(-32768.0);c=(-32768.0);"],
  ["negative literal", "a=-1 b=x-1 c=x- -1", "a=(-1.0);b=(x-1.0);c=(x-(-1.0));"],
  ["c-style comment", "a=1 // comment\nb=2", "a=1.0;\nb=2.0;"],
  ["long comment keeps lines", "--[[ a\nb ]] x=1\ny=2", "\nx=1.0;\ny=2.0;"],
  ["string p8 escapes", "s=\"\\^w\\#1\\*\\|\\+\\-\\a\\014\"", "s=\"\\006w\\0021\\001\\004\\005\\003\\007\\014\";"],
  ["string glyphs", "s=\"❎🅾️\"", "s=\"\\151\\142\";"],
  ["long string", "s=[[a\n\"b\"]]", "s=\"a\\n\\\"b\\\"\";"],
  ["length is float", "n=#t", "n=(#t+0.0);"],
  ["glyph identifier", "❎=1", "__p8i_97=1.0;"],
  ["precedence", "a=1+2*3^2 b=not a==b c=-x^2", "a=(1.0+(2.0*(3.0^2.0)));b=((not a)==b);c=(-(x^2.0));"],
  ["concat right assoc", "a=b..c..d", "a=__p8_cat(b,__p8_cat(c,d));"],
  ["method and string call", "o:m\"s\" f{1,2}", "o:m(\"s\");f({1.0,2.0,});"],
  ["table constructor", "t={1,x=2,[3]=4}", "t={1.0,x=2.0,[3.0]=4.0,};"],
  ["labels and goto", "::top:: goto top", "::top_1::goto top_1;"],
  ["nested label reuse (Lua 5.2 semantics)", "::y:: do goto y ::y:: end", "::y_1::do goto y_2;::y_2::end;"],
  ["print as expression", "c=?\"w\"", "c=print(\"w\");"],
  ["local function", "local function f(...) return ... end", "local function f(...)return...;end"],
  ["repeat until", "repeat i+=1 until i>3", "repeat i=(i+(1.0));until(i>3.0);"],
  ["numeric for", "for i=10,1,-1 do end", "for i=10.0,1.0,(-1.0)do end;"],
  ["generic for", "for k,v in pairs(t) do end", "for k,v in pairs(t)do end;"],
];
